### ISSUE TITLE
document settings

### ISSUE THREAD

**Issue by thenewguy** [WoLpH/django-statsd#10]
It would be helpful to document the available settings.  Attempting to configure this for the first time and reading through the source code to figure it out but there are a lot of moving pieces.  I am not familiar enough with any of this to be of any help but figured I would open the issue

**Comment by WoLpH** [comment]
It seems that's indeed lacking from the documentation. Actually, all docs are a bit limited and in need of some improvement.

You can see a list of the settings in the demo application for now:
https://github.com/WoLpH/django-statsd/blob/master/tests/settings.py#L155-L158

**Comment by WoLpH** [comment]
The settings are now documented: http://django-stats.readthedocs.io/en/latest/django_statsd.html#module-django_statsd.settings
