### ISSUE TITLE
Update to support Django 1.10 MIDDLEWARE as well as MIDDLEWARE_CLASSES

### ISSUE THREAD

**Issue by danizen** [WoLpH/django-statsd#12]
Should be pretty simple if the lowest supported version becomes Django 1.10

https://docs.djangoproject.com/en/2.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by WoLpH** [comment]
The code is indeed fairly easy to port but it's the tests where it's a tad more work to support multiple django versions. I've done some work on that but nothing finished unfortunately :(

Simply renaming the middlewares is not enough I'm guessing, the django middlewares system has changed a bit internally as well

**Comment by danizen** [comment]
django-cas-ng is a package I've contributed to where tox is used to vary not just the python version but also the Django version.  I have my hands full, but if I free up I'll take a stab at that.

**Comment by WoLpH** [comment]
All help is greatly appreciated so if you are willing to try and have the time, please do :)

**Comment by WoLpH** [comment]
I've pushed out a new release wich support Django 1.11 and 2.0 :)
