### ISSUE TITLE
Add logger client

### ISSUE THREAD

**Issue by patoroco** [WoLpH/django-statsd#15]
During development, should be really helpful to have a dummy statsd client that instead of try to send the metrics to the real statsd, it just print logs with the metrics that you're trying to send.

**Comment by WoLpH** [comment]
That's easily done actually :)
First, set the statsd client to point to a non-existing statsd server. Since it uses udp it won't care if the server exists or not, it will silently fail.
Second, set the logging for `statsd` to `info` or higher.

So... something along these lines:
```python
# Settings:
STATSD_HOST = '127.0.0.1'
STATSD_PORT = 12345

# Set the log level
import logging
logger = logging.getLogger('statsd')
logger.setLevel(logging.INFO)

# If you don't have any logging setup yet
logger.addHandler(logging.StreamHandler())
```

**Comment by patoroco** [comment]
Sorry by my late answer, but I haven't had time to do it before...

Thanks to your response @WoLpH, I enabled the logs in my Django and it works as expected, but the client continued trying to send metrics to the server (with your config, to `127.0.0.1`), so after read [the statsd code](https://github.com/WoLpH/python-statsd/blob/a757da04375c48d03d322246405b33382d37f03f/statsd/connection.py#L38), I've added this parameter in the #16, hoping to help more users :)
