### ISSUE TITLE
Every 404 error causes regex error from skip_view

### ISSUE THREAD

**Issue by 0pt1c** [WoLpH/django-statsd#19]
We are experiencing an issue with our django app where anytime there is a 404 error, the `skip_view` function tries to match against a view without a name, and then regex throws an error trying to match against `None`.

After a little more investigation the view it is trying to compare to is the `StatsdMiddleware` which has a `view_name` of `None`

![screenshot_7](https://user-images.githubusercontent.com/2586233/77662555-a204c380-6f41-11ea-8a1b-6ff9bb54ac19.png)

```
    if re.match(pattern, view_name):
  File "/usr/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

This is causing a 500 error for every 404.

I'm not sure if we have something misconfigured somewhere or if this is a bug of some kind. Does anyone have any insight or advice about this problem?

**Comment by WoLpH** [comment]
I'm guessing it's simply a bug to be honest. This code was recently added through a pull request and I probably didn't check it well enough.

But there is one alternative option. The `view_name` is set by the `StatsdMiddleware` so if it's too low in the list of middlewares it could be that it's not setting it.

In any case, the code should be a bit more defensive about assuming that variables exist. I've patched the code and I'll create a new release today :)

**Comment by WoLpH** [comment]
The new release is online

**Comment by 0pt1c** [comment]
Thanks for looking at this and getting a fix out so quickly!
