### ISSUE TITLE
Document/support instrumentation of database

### ISSUE THREAD

**Issue by danizen** [wolph/django-statsd#20]
I'm comparing this with the [django-statsd-mozilla](https://pypi.org/project/django-statsd-mozilla/) package.  Both work out of the box, but the other better supports SQL and cache timing.  On the other hand, your package has a recent pull request and covers json parse/load and rendering time.  Have you given any thought to finishing the work in `django_statsd.database`?   Would you be open to a pull request to do so?

**Comment by WoLpH** [comment]
The package should support database tracking as well. is there anything specific you're missing?

https://www.github.com/WoLpH/django-statsd/tree/master/django_statsd%2Fdatabase.py

**Comment by WoLpH** [comment]
In any case, I'm always open to pull requests

**Comment by danizen** [comment]
I followed the terse documentation, but the database and middleware tracking didn't work out of the box. 

Where is the code that installs that cursor wrapper?

Is this a case where you thought installing it yourself might violate the principle of least surprise?

BTW, I have a custom database backend for postgresql that gets the password from AWS Secrets Manager, and then caches it.  If it ever gets an authentication failure when making a connection, it goes back to AWS Secrets Manager and gets it again.  Zero downtime and automatic password rotation.  We are planning to use it for all the Django applications as they migrate to the cloud - I am hoping to mandate usage of statsd as well.

**Comment by WoLpH** [comment]
The documentation is indeed lacking quite a bit. When I initially wrote the project I was using it for my systems quite a bit but it seems I forgot to document this part entirely.

Usage is actually not that hard because Django already has a `CursorWrapper` that you can monkeypatch. But looking at the Django internals a few things have changed slightly making the monkeypatch slightly more manual (or requiring a new class which inherits both). Regardless, I think the following should work:

```
import django_statsd


def install_database_monkeypatch():
    try:
        from django.db.backends.utils import CursorWrapper
    except ImportError:
        from django.db.backends.util import CursorWrapper

    try:
        orig_execute = CursorWrapper.execute
        orig_executemany = CursorWrapper.executemany
    except AttributeError:
        return

    def execute(self, *args, **kwargs):
        with django_statsd.with_('sql.%s' % self.db.alias):
            return orig_execute(self, *args, **kwargs)

    def executemany(self, *args, **kwargs):
        with django_statsd.with_('sql.%s' % self.db.alias):
            return orig_executemany(self, *args, **kwargs)

    CursorWrapper.execute = execute
    CursorWrapper.executemany = executemany
```
