### ISSUE TITLE
Settings evaluation on import prevents try/catch inclusion in Django settings

### ISSUE THREAD

**Issue by adam-iris** [WoLpH/django-statsd#22]
We typically wrap all non-critical components in a try/catch block in Django's `settings.py`, ie.

```python
STATSD_PREFIX = 'django'
try:
    import django_statsd
    INSTALLED_APPS += (
        'django_statsd',
    )
    MIDDLEWARE = (
        'django_statsd.middleware.StatsdMiddleware',
    ) + MIDDLEWARE + (
        'django_statsd.middleware.StatsdMiddlewareTimer',
    )
except:
    pass
```

But because `django_statsd` evaluates its own settings in the import, this happens before the Django-level settings have actually been registered, so it doesn't see any of them (ie. `STATSD_PREFIX` here doesn't get picked up)

Honestly, this doesn't look fixable without major changes, so I'm planning to work around it. But it seemed worth raising in case I'm wrong about that.

**Comment by WoLpH** [comment]
Fixing it would not be impossible but it would take a bit of effort.

We can easily work around the issue in your case however... it's not a pretty fix but quite effective:

```python
import sys
for module in list(sys.modules):
    if module.split('.', 1)[0] == 'django_statsd':
        del sys.modules[module]
```

**Comment by adam-iris** [comment]
This works, sort of -- it also appears to output a bunch of metrics on import, which get sent to the default host (127.0.01). I noticed this when running on a box without a local statsd server, it logged a bunch of errors. If the localhost has a statsd server that *shouldn't* be used, that might be a bigger problem.

[This StackOverflow post](https://stackoverflow.com/a/14050282/1005790) seems to describe a workaround, but it's version-dependent. In our case, I think we can assume Python 3.4+, but as a general solution it seems pretty unwieldy.

At any rate, this solves my particular issue, so I'm fine with closing this ticket.
