### ISSUE TITLE
Current 2.5.2 release mismatch the latest code

### ISSUE THREAD

**Issue by mmz2000** [WoLpH/django-statsd#23]
2.5.2 is tagged as latest but both in document and source code mismatch exists
the breaking part fixed in the latest is `is_ajax` function which is not released.

**Comment by sirjoe** [comment]
Hi, I came across the same issue just yesterday. 
Could you please release a new version to PyPI?

**Comment by sirjoe** [comment]
@mmz2000 What's your workaround for this? I simply refer to the master branch `django-statsd = { git = "https://github.com/wolph/django-statsd.git", branch = "master"}`, However this makes our service rather brittle.

Did you manage to find an alternative to this library?

**Comment by mmz2000** [comment]
@sirjoe yes I used the same work around for installing the latest
To be safer you can use the commit hash or tags
We eventually didn't use this package since we dropped statsd in favor of prometheus and loki

**Comment by wolph** [comment]
oops... sorry about that, I wasn't aware that there were differences. I'll release a new version within a week.

**Comment by sirjoe** [comment]
Thanks @wolph , looking forward to the new version :)

**Comment by sirjoe** [comment]
any update @wolph ?

**Comment by wolph** [comment]
@sirjoe Getting all tests up to date and fixed is taking a bit more time than I had anticipated. I've already pushed out a new release that works, but the CI system still isn't happy yet so I'm working on that :)

**Comment by mmz2000** [comment]
Thanks @wolph

**Comment by wolph** [comment]
Oops... forgot to close this but both the CI system and the release have been fixed for a while :)
